[versions]
detekt = "1.22.0"
kotlin = "1.7.21"
ktlintGradle = "11.0.0"
pluginPublish = "1.1.0"
versionCheck = "0.44.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle"}
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck"}

[libraries]
junit = "junit:junit:4.13.2"
