[versions]
detekt = "1.23.4"
kotlin = "1.9.22"
ktlintGradle = "12.1.0"
pluginPublish = "1.2.1"
versionCheck = "0.51.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle"}
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck"}

[libraries]
junit = "junit:junit:4.13.2"
