[versions]
detekt = "1.23.8"
kotlin = "2.2.10"
ktlintGradle = "13.0.0"
pluginPublish = "1.3.1"
versionCheck = "0.52.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle"}
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck"}

[libraries]
junit = "junit:junit:4.13.2"
